-- Oracle Datastore Agent Database Initialization Script
-- This script sets up the database for the Oracle Datastore Agent
ALTER SESSION SET CONTAINER = FREEPDB1;
-- Create application user
CREATE USER datastore_user IDENTIFIED BY datastore_pass;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE TO datastore_user;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE ANY INDEX TO datastore_user;
GRANT CREATE PROCEDURE TO datastore_user;
GRANT UNLIMITED TABLESPACE TO datastore_user;

-- Grant JSON privileges
GRANT EXECUTE ON DBMS_JSON TO datastore_user;

-- Create tablespace for the application
CREATE TABLESPACE datastore_ts
DATAFILE 'datastore_llm_ts.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- Grant tablespace quota
ALTER USER datastore_user QUOTA UNLIMITED ON datastore_ts;

-- Create sample tables for testing
CREATE TABLE datastore_user.sample_json_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    json_data JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE datastore_ts;

CREATE TABLE datastore_user.sample_text_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content CLOB,
    content_vector VECTOR,
    content_hash VARCHAR2(64),
    word_count NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE datastore_ts;

CREATE TABLE datastore_user.sample_binary_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binary_data BLOB,
    file_name VARCHAR2(255),
    mime_type VARCHAR2(100),
    file_size NUMBER,
    file_hash VARCHAR2(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE datastore_ts;

-- Create indexes
CREATE INDEX idx_sample_json_created ON datastore_user.sample_json_data(created_at);
CREATE INDEX idx_sample_text_created ON datastore_user.sample_text_data(created_at);
CREATE INDEX idx_sample_binary_created ON datastore_user.sample_binary_data(created_at);

-- Insert sample data
INSERT INTO datastore_user.sample_json_data (json_data) VALUES (
    JSON_OBJECT(
        'name' VALUE 'Sample User',
        'email' VALUE 'sample@example.com',
        'active' VALUE true,
        'role' VALUE 'user'
    )
);

INSERT INTO datastore_user.sample_text_data (content, word_count) VALUES (
    'This is a sample text document for testing the Oracle Datastore Agent with AI Vector Search capabilities.',
    15
);

COMMIT;

-- Display completion message
SELECT 'Oracle Datastore Agent database initialization completed successfully!' as message FROM DUAL;



